#cloud-config
write_files:
  - path: /etc/docker-install.sh
    owner: root
    permissions: 0766
    content: |
      #!bin/bash
      sudo apt update && apt upgrade -y
      sudo apt install curl apt-transport-https ca-certificates software-properties-common -y 
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt update -y
      sudo apt install docker-ce -y
      sudo systemctl start jenkins.service

  - path: /etc/systemd/system/jenkins.service
    owner: root
    permissions: 0755
    command: start
    content: |
      [Unit]
      Description=Jenkins

      [Service]
      SyslogIdentifier=docker-jenkins
      ExecStartPre=-/usr/bin/docker pull jenkins/jenkins:lts-jdk11
      ExecStartPre=-/usr/bin/docker create -m 0b -p 8989:8080 -p 50000:50000 --restart=always --name jenkins jenkins/jenkins:lts-jdk11
      ExecStart=/usr/bin/docker start -a jenkins
      ExecStop=-/usr/bin/docker stop --time=0 jenkins
      Restart=always
      RestartSec=10s
      TimeoutStartSec=0
      TimeoutStopSec=15

      [Install]
      WantedBy=multi-user.target

runcmd:
  - sudo bash /etc/docker-install.sh